server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat_mp?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379

wx:
  mp:
    app-id: wxf29431fbf84c322b
    secret: 1606f0fb81850b53208c7a57b056498a
    token: token
    aes-key: test

mybatis:
  type-aliases-package: com.wechat.web.domain

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.wechat.web.domain


jwt:
  key: cyh


file:
  ###静态资源对外暴露的访问路径
  staticAccessPath: /static/**
  ###静态资源实际存储路径
  uploadFolder: D:\staticResource\upload\